name:                reach
version:             0.1.0
github:              "reach-sh/reach-lang"
license:             Apache-2.0
author:              "Reach"
maintainer:          "jay@reach.sh"
copyright:           "2019 Reach"
description:         Please visit the GitHub repository <https://github.com/reach-sh/reach-lang#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- prettyprinter
- bytestring
- mtl
- digest
- language-javascript >= 0.6.0.13
- parsec-numbers
- filepath
- file-embed >= 0.0.9
- optparse-applicative
- directory
- process
- pretty-simple
- text
- extra
- simple-smt
- aeson
- unordered-containers
- system-filepath
- lattices
- hspec
- smallcheck
- hspec-smallcheck
- generic-deriving
- deepseq
- hexstring
- haskell-evm
- cryptonite
- memory
- base64
- loop

ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -O2
- -fwrite-ide-info
- -hiedir=.hie

library:
  source-dirs: src

executables:
  reachc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reach

tests:
  reach-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reach
